[package]
name = "pg_query"
description = "PostgreSQL parser that uses the actual PostgreSQL server source to parse SQL queries and return the internal PostgreSQL parse tree."
version = "0.1.0"
authors = ["Paul Mason <paul@form1.co.nz>"]
edition = "2018"
documentation = "https://docs.rs/pg_query.rs/"
build = "build.rs"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/paupino/pg_query.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "0.8", features = ["serde"] }

[build-dependencies]
bindgen = "0.58"
clippy = { version = "0", optional = true }
convert_case = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
